name: Type Check

on:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sync
        run: uv sync

      - name: Run pyright
        run: uv run pyright