name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs: # job は別マシンで並列に実行される
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Sync
        run: uv sync --group dev --group auto_test

      - name: Run pyright
        run: uv run pyright
      
      - name: Ruff check
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --check .

      - name: Generate snippets
        run: uv run python tools/snippets_generater.py

      - name: Check snippets diff
        run: git diff --exit-code --ignore-cr-at-eol
  
  library-checker:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Sync
        run: uv sync --group library_checker

      - name: Run library_checker tests
        run: |
          set -o pipefail
          uv run oj-verify run --timeout 1800 --jobs 2 2>&1 \
          | sed 's/\x1b\[[0-9;]*m//g' \
          | tee result.log \
          | grep --line-buffered -E "INFO:onlinejudge_verify.verify:(verify|problem):|\[SUCCESS\] test success:|\[FAILURE\] (test failed:|WA|TLE|RE|PE)" \
          || test ${PIPESTATUS[0]} -eq 0
      
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result-log
          path: result.log